spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/shop
spring.datasource.username=egor
spring.datasource.password=egor987
spring.datasource.driver-class-name=org.postgresql.Driver