services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend-network
  
  users-service:
    container_name: users-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - backend-network

  nginx:
    image: nginx
    container_name: nginx-server
    ports:
      - '8070:8080'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - backend-network
    depends_on:
      - users-service
      - auth-service

networks:
  backend-network:
    external: true
    driver: bridge

