spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/shop-test
spring.datasource.username=postgres
spring.datasource.password=TujH9889HjuT

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate.ddl=false