spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://postgres-shop:5432/shop
spring.datasource.username=egor
spring.datasource.password=egor987
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate.ddl=false
jwt.secret=4xum1Bz31iPsRNpSEi7d3VJnfeTs7ucK0OCOX0DeUSk